baseURL = "https://andriesei.github.io/intruzive/"
locale = "ro-ro"
title = "Gânduri Intruzive"
theme = "dark-theme-editor"
enableGitInfo = true

[params.header]
  title = "Gânduri Intruzive"
  subtitle = false
  
[params.globalFrontmatter]
  author = "Andrei"
  description = "Un jurnal de gânduri"
  keywords = "jurnal, ganduri, reflectii"

[params.homePage]
  siteLongDescription = "Fragmente scrise în zile diferite, fără pretenția de a fi complete."
  siteLongDescriptionTitle = "Despre"
  showRecentPostsBlock = true
  numOfRecentPosts = 5
  recentPostShowUrl = false

[params.site]
  faviconUrl = "/favicon.svg"
  localCss = ["css/background.css"]

[params.footer]
  copyrightStr = ""
  gitHash = false