baseURL = "https://andriesei.github.io/intruzive/"
locale = "ro-ro"
title = "Gânduri Intruzive"
theme = "dark-theme-editor"
enableGitInfo = true

[params.header]
  title = "Gânduri Intruzive"
  subtitle = false
  
[params.globalFrontmatter]
  author = "Andrei"
  description = "Un jurnal de gânduri"
  keywords = "jurnal, ganduri, reflectii"

[params.homePage]
  siteLongDescription = "Fragmente scrise în zile diferite, fără pretenția de a fi complete."
  siteLongDescriptionTitle = "Despre"
  showRecentPostsBlock = true
  numOfRecentPosts = 5
  recentPostShowUrl = false
  showManifestCard = true
  manifestTitle = "Manifest"
  manifestText = "Proiectul de față este un drum provocator, atât pentru autor, cât și pentru cititor, în căutarea înțelegerii a ceea ce înseamnă a fi uman în raport cu existența. Pe lângă aceasta, este tratată contradicția dintre nevoia omului de a da sens și riscul ca sensurile, definițiile și etichetele prin care încearcă să se înțeleagă să-l îndepărteze tocmai de ceea ce încearcă să înțeleagă. Aici nu căutăm să eliminăm obstacolele, ci să le observăm."

[params.site]
  faviconUrl = "/favicon.svg"
  localCss = ["css/background.css"]

[params.footer]
  copyrightStr = ""
  gitHash = false